image: python:latest

services:
  - mariadb:latest

variables:
  MYSQL_DATABASE: "caster_dashboard"
  MYSQL_ROOT_PASSWORD: mysql

stages:
  - build
  - test

before_script:
  - python -V
  - pip install -r requirements.txt

Build:
  stage: build
  script:
    - python manage.py test